[tool.pylint.'MASTER']
# https://docs.splunk.com/Documentation/Splunk/9.3.0/Python3Migration/PythonCompatibility
py-version = "3.7"
init-hook='import sys; sys.path.append("./bin")'

[tool.pylint.'FORMAT']
indent-after-paren = 4
indent-string = "    "
expected-line-ending-format="LF"

[tool.ruff]
line-length = 115
# Module level import not at top of file (`E402`).
ignore = ["E402"]
